{{- if .Values.orderProcessing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing
  labels:
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: order-processing
spec:
  replicas: {{ .Values.orderProcessing.deployment.replicas }}
  selector:
    matchLabels:
      {{- if .Values.selectorLabels }}
      {{- toYaml .Values.selectorLabels | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: order-processing
  template:
    metadata:
      labels:
        {{- if .Values.labels }}
        {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: order-processing
    spec:
      serviceAccountName: {{ .Values.orderProcessing.serviceAccount.name }}
      containers:
      - name: order-processing
        image: "{{ .Values.imageRegistry }}/{{ .Values.orderProcessing.image.repository }}:{{ .Values.orderProcessing.image.tag }}"
        imagePullPolicy: {{ .Values.orderProcessing.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: sns-sqs-config
              key: AWS_REGION
        - name: SQS_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: sns-sqs-config
              key: SQS_QUEUE_1_URL
        {{- if .Values.otlp.enabled }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.otlp.endpoint }}
        {{- if .Values.otlp.insecure }}
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: {{ .Values.otlp.insecure | quote }}
        {{- end }}
        {{- if .Values.otlp.headers }}
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: {{ .Values.otlp.headers | quote }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.orderProcessing.deployment.resources | nindent 10 }}
      restartPolicy: Always
{{- end }}

