{{- if .Values.producer.enabled }}
{{- if not .Values.producer.job.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: producer
spec:
  replicas: {{ .Values.producer.deployment.replicas }}
  selector:
    matchLabels:
      {{- if .Values.selectorLabels }}
      {{- toYaml .Values.selectorLabels | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: producer
  template:
    metadata:
      labels:
        {{- if .Values.labels }}
        {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: producer
    spec:
      serviceAccountName: {{ .Values.producer.serviceAccount.name }}
      containers:
      - name: producer
        image: "{{ .Values.imageRegistry }}/{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}"
        imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: sns-sqs-config
              key: AWS_REGION
        - name: SNS_TOPIC_ARN
          valueFrom:
            configMapKeyRef:
              name: sns-sqs-config
              key: SNS_TOPIC_ARN
        resources:
          {{- toYaml .Values.producer.deployment.resources | nindent 10 }}
      restartPolicy: Always
{{- end }}
{{- end }}

