{{- if .Values.notification.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: notification
spec:
  replicas: {{ .Values.notification.deployment.replicas }}
  selector:
    matchLabels:
      {{- if .Values.selectorLabels }}
      {{- toYaml .Values.selectorLabels | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: notification
  template:
    metadata:
      labels:
        {{- if .Values.labels }}
        {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: notification
    spec:
      serviceAccountName: {{ .Values.notification.serviceAccount.name }}
      containers:
      - name: notification
        image: "{{ .Values.imageRegistry }}/{{ .Values.notification.image.repository }}:{{ .Values.notification.image.tag }}"
        imagePullPolicy: {{ .Values.notification.image.pullPolicy }}
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: sns-sqs-config
              key: AWS_REGION
        - name: SQS_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: sns-sqs-config
              key: SQS_QUEUE_2_URL
        resources:
          {{- toYaml .Values.notification.deployment.resources | nindent 10 }}
      restartPolicy: Always
{{- end }}

