apiVersion: v2
name: sns-sqs-microservices
description: A Helm chart for SNS/SQS microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - sns
  - sqs
  - aws
  - microservices
  - messaging
maintainers:
  - name: esara

